#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-BoolNet
Version  : 2.1.9
Release  : 45
URL      : https://cran.r-project.org/src/contrib/BoolNet_2.1.9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/BoolNet_2.1.9.tar.gz
Summary  : Construction, Simulation and Analysis of Boolean Networks
Group    : Development/Tools
License  : Artistic-2.0
Requires: R-BoolNet-lib = %{version}-%{release}
Requires: R-XML
Requires: R-igraph
BuildRequires : R-XML
BuildRequires : R-igraph
BuildRequires : buildreq-R

%description
No detailed description available

%package lib
Summary: lib components for the R-BoolNet package.
Group: Libraries

%description lib
lib components for the R-BoolNet package.


%prep
%setup -q -n BoolNet
pushd ..
cp -a BoolNet buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1696348537

%install
export SOURCE_DATE_EPOCH=1696348537
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/BoolNet/CITATION
/usr/lib64/R/library/BoolNet/DESCRIPTION
/usr/lib64/R/library/BoolNet/INDEX
/usr/lib64/R/library/BoolNet/Meta/Rd.rds
/usr/lib64/R/library/BoolNet/Meta/data.rds
/usr/lib64/R/library/BoolNet/Meta/features.rds
/usr/lib64/R/library/BoolNet/Meta/hsearch.rds
/usr/lib64/R/library/BoolNet/Meta/links.rds
/usr/lib64/R/library/BoolNet/Meta/nsInfo.rds
/usr/lib64/R/library/BoolNet/Meta/package.rds
/usr/lib64/R/library/BoolNet/Meta/vignette.rds
/usr/lib64/R/library/BoolNet/NAMESPACE
/usr/lib64/R/library/BoolNet/NEWS.Rd
/usr/lib64/R/library/BoolNet/R/BoolNet
/usr/lib64/R/library/BoolNet/R/BoolNet.rdb
/usr/lib64/R/library/BoolNet/R/BoolNet.rdx
/usr/lib64/R/library/BoolNet/data/cellcycle.rda
/usr/lib64/R/library/BoolNet/data/examplePBN.rda
/usr/lib64/R/library/BoolNet/data/igf.rda
/usr/lib64/R/library/BoolNet/data/yeastTimeSeries.rda
/usr/lib64/R/library/BoolNet/doc/BoolNet_package_vignette.R
/usr/lib64/R/library/BoolNet/doc/BoolNet_package_vignette.Snw
/usr/lib64/R/library/BoolNet/doc/BoolNet_package_vignette.pdf
/usr/lib64/R/library/BoolNet/doc/cellcycle.txt
/usr/lib64/R/library/BoolNet/doc/example.btp
/usr/lib64/R/library/BoolNet/doc/index.html
/usr/lib64/R/library/BoolNet/help/AnIndex
/usr/lib64/R/library/BoolNet/help/BoolNet.rdb
/usr/lib64/R/library/BoolNet/help/BoolNet.rdx
/usr/lib64/R/library/BoolNet/help/aliases.rds
/usr/lib64/R/library/BoolNet/help/paths.rds
/usr/lib64/R/library/BoolNet/html/00Index.html
/usr/lib64/R/library/BoolNet/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/BoolNet/libs/BoolNet.so
/usr/lib64/R/library/BoolNet/libs/BoolNet.so.avx2
/usr/lib64/R/library/BoolNet/libs/BoolNet.so.avx512
